[project]
name = "llmgateway"
version = "0.1.0"
description = ""
authors = [
    {name = "user",email = "user@user.com"}
]
readme = "README.md"
requires-python = "3.13.5"
dependencies = [
    "apscheduler (>=3.11.0,<4.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "flask (>=3.1.2,<4.0.0)",
    "requests (>=2.32.5,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
